---
name: Install NSIS if not cached
description: This action installs NSIS if it was not previously cached
runs:
  using: composite
  steps:
    - name: Set up cache for NSIS v2.46
      id: cache_NSIS
      uses: actions/cache@v3
      with:
        path: C:\Program Files (x86)\NSIS
        key: ${{ runner.os }}-nsis
    - name: Install NSIS if not cached
      if: steps.cache_NSIS.outputs.cache-hit != 'true'
      shell: pwsh
      run: |-
        [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
        choco install nsis.install --version=2.46 -y -dv
