name: GitHub Action Validation

on:
  push:
    branches:
      - feature/**
    paths:
      - .github/**
  workflow_dispatch:

env:
  # See: https://lyz-code.github.io/yamlfix/#configuration-options
  YAMLFIX_EXPLICIT_START: false
  YAMLFIX_SECTION_WHITELINES: 1
  YAMLFIX_SEQUENCE_STYLE: block_style

jobs:
  yaml_validation:
    # if: contains(github.event.head_commit.message, '[run yamlfix]')
    name: Validate GitHub YAML Files using Lint
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ steps.job_status.outputs.status }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN  }}

      # Use YamlLint to validate .yml files
      - name: Validate YAML files
        id: yamllint
        continue-on-error: true
        run: yamllint -d relaxed .
      - name: Set job status
        id: job_status
        run: |
          if [ ${{ steps.yamllint.outcome }} != 'success' ]
          then
            echo "status=FAILED" >> $GITHUB_OUTPUT
          else
            echo "status=SUCCESS" >> $GITHUB_OUTPUT
          fi
      - name: Debugging information
        run: |
          echo ${{ steps.job_status.outputs.status }}
          echo ${{ steps.yamllint.outcome }}
  yamlfix:
    needs: yaml_validation
    if: ${{ always() && contains(join(needs.yaml_validation.outputs.job_status, ','), 'FAILED') }}
    name: Fix GitHub YAML Files using Yamlfix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN  }}

      # Install Yamlfix: https://lyz-code.github.io/yamlfix/
      - name: Install Yamlfix
        run: pip install Yamlfix

      # Run Yamlfix, only if yamllint detected errors.
      - name: Run Yamlfix
        run: yamlfix .

      # Check for Yamlfix changes
      - name: Check for changes
        id: yamlfix_check
        run: echo "code_changed=$(git status --porcelain | head -n 1)" >> $GITHUB_OUTPUT

      # Commit the Yamlfix changes
      - name: Commit Yamlfix changes
        if: ${{ steps.yamlfix_check.outputs.code_changed }}
        run: |-
          echo "Committing yamlfix fixes"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m 'Yamlfix automatic changes'
          git push
  action_validation:
    needs:
      - yaml_validation
      - yamlfix
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v2
        with:
          tool_versions: |
            action-validator 0.5.1
      - name: Validate Actions
        id: validate_actions
        continue-on-error: true
        run: |
          find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
            | xargs -I {} action-validator --verbose {} > workflow_error_report.txt 2>&1
      - name: Upload Validation error report
        if: steps.validate_actions.outcome != 'success'
        uses: actions/upload-artifact@v3
        with:
          name: Workflow Validation Report
          path: |-
            workflow_error_report.txt
