on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    
    steps:
      - uses: actions/checkout@v3
        
      # This is for PRIVATE actions only.  Multiple actions within a repo is only allowed for private actions.
      # If you'd like to share actions across repos, each action must be within it's own repo.
      # Then call those private actions as you normally would for public actions.
      # eg 'uses: actions/checkout@v3' so something like:
      # 'uses: WhittenJ/template_composite@v1'
      # 'uses: WhittenJ/template_script@v1'
      
      - name: Example for Composite Actions
        uses: ./.github/actions/template_composite
        
      - name: Example for Composite Actions with Script and Inputs
        id: foo
        uses: ./.github/actions/template_script
        with:
          who-to-greet: 'Mona the Octocat'
          
      - name: Example for Docker Action
        uses: ./.github/actions/template_docker
          
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash