name: GitHub Action Validation

on:
  push:
    branches:
      - feature/**
    paths:
      - .github/**
  workflow_dispatch:

env:
  # See: https://lyz-code.github.io/yamlfix/#configuration-options
  YAMLFIX_EXPLICIT_START: false
  YAMLFIX_SECTION_WHITELINES: 1
  YAMLFIX_SEQUENCE_STYLE: block_style

jobs:
  action_validation:
    if: contains(github.event.head_commit.message, '[run yamlfix]')
    name: Validate GitHub Actions using Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN  }}

      # Use YamlLint to validate .yml files
      - name: Validate YAML files
        id: yamllint
        continue-on-error: true
        run: yamllint -d relaxed .

      # Install Yamlfix: https://lyz-code.github.io/yamlfix/
      - name: Install Yamlfix
        if: steps.outcome.yamllint != 'success'
        run: pip install Yamlfix

      # Run Yamlfix
      - name: Run Yamlfix
        if: steps.outcome.yamllint != 'success'
        run: yamlfix .

      # Check for Yamlfix changes
      - name: Check for changes
        if: steps.outcome.yamllint != 'success'
        id: yamlfix_check
        run: echo "code_changed=$(git status --porcelain | head -n 1)" >> $GITHUB_OUTPUT
      
      # Commit the Yamlfix changes
      - name: Commit Yamlfix changes
        if: ${{ steps.yamlfix_check.outputs.code_changed }}
        run: |-
          echo "Committing yamlfix fixes"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m 'Yamlfix automatic changes'
          git push
